name: cupy
channels:
  - defaults
dependencies:
  - python=3.11
  - Cython>=3.0.0
  - pytest>=6.2.4
  - pytest-benchmark>=3.4.1
  - numpy>=1.21.1
  - pyclibrary>=0.1.7
  - setuptools
  - versioneer==0.29
  - wheel
  - pip
  - pip:
    - pytest-benchmark>=3.4.1
