name: cuda-python-docs
channels:
  - conda-forge
dependencies:
  - cython=0.29.23
  - myst-parser
  - matplotlib
  - numba
  - numpy
  - pip
  - pydata-sphinx-theme
  - pytest
  - scipy
  - sphinx
  - pip:
    - myst-nb
