name: "CI"

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-build-and-test-on-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "main"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        # TODO: align host-platform names with conda convention
        host-platform:
          - linux-x64
          - linux-aarch64
          - win-x64
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        cuda-version:
          # Note: this is for build-time only; the test-time matrix needs to be
          # defined separately.
          - "12.6.2"
    name: "CI"
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      host-platform: ${{ matrix.host-platform }}
      python-version: ${{ matrix.python-version }}
      cuda-version: ${{ matrix.cuda-version }}
    secrets: inherit
