on:
  workflow_call:
    inputs:
      target-device:
        type: string
        required: true
      build-type:
        type: string
        required: true
      host-platform:
        type: string
        required: true
      build-mode:
        type: string
        required: true
      upload-enabled:
        type: boolean
        required: true
      python-version:
        type: string
        required: true
      cuda-version:
        type: string
        required: true

jobs:
  build:
    name: Build wheels
    if: ${{ github.repository_owner == 'nvidia' }}
    uses:
      ./.github/workflows/gh-build.yml
    with:
      client-repo: ${{ github.event.repository.name }}
      target-device: ${{ inputs.target-device }}
      runs-on: ${{ (inputs.host-platform == 'linux-x64' && 'linux-amd64-cpu8') ||
                   (inputs.host-platform == 'linux-aarch64' && 'linux-arm64-cpu8') ||
                   (inputs.host-platform == 'win-x64' && 'windows-2019') }}
                 #  (inputs.host-platform == 'win-x64' && 'windows-amd64-cpu8') }}
      build-type: ${{ inputs.build-type }}
      host-platform: ${{ inputs.host-platform }}
      build-mode: ${{ inputs.build-mode }}
      upload-enabled: ${{ inputs.upload-enabled }}
      python-version: ${{ inputs.python-version }}
      cuda-version: ${{ inputs.cuda-version }}
      dependencies-file: ""
    secrets: inherit

  test:
    name: Test against wheels
    # TODO: enable testing once linux-aarch64 & win-64 GPU runners are up
    if: ${{ (github.repository_owner == 'nvidia') &&
             startsWith(inputs.host-platform, 'linux-x64') }}
    needs:
      - build
    uses:
      ./.github/workflows/gh-test.yml
    with:
      client-repo: ${{ github.event.repository.name }}
      target-device: ${{ inputs.target-device }}
      test-options: ${{ inputs.build-type }}
      runs-on: ${{ (inputs.host-platform == 'linux-x64' && 'linux-amd64-gpu-v100-latest-1') }}
      build-type: ${{ inputs.build-type }}
      host-platform: ${{ inputs.host-platform }}
      dependencies-file: ""
      build-mode: ${{ inputs.build-mode }}
      upload-enabled: ${{ inputs.upload-enabled }}
      python-version: ${{ inputs.python-version }}
      has-built: ${{ needs.build.outputs.has-built }}
    secrets: inherit
