name: Test

on:
  workflow_call:
    inputs:
      client-repo:
        required: true
        type: string
      build-type:
        required: true
        type: string
      name:
        required: true
        type: string
      target-device:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      has-gpu:
        required: true
        type: boolean
        description: "The runner has GPU(s)."
      test-options:
        required: true
        type: string
      platform:
        required: true
        type: string
      build-mode:
        required: true
        type: string
      upload-enabled:
        required: true
        type: boolean
      python-version:
        required: false
        type: string

jobs:
  test:
    name: ${{ inputs.name }}
    if: github.repository_owner == 'nvidia'
    runs-on: ${{ inputs.runs-on }}

    container:
      options: -u root --security-opt seccomp=unconfined --privileged --shm-size 16g
      image: condaforge/miniforge3:latest
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash --noprofile --norc -xeuo pipefail {0}

    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          client-repo: ${{ inputs.client-repo }}
          build-type: ${{ inputs.build-type }}
          target-device: "${{ inputs.target-device }}"
          platform: ${{ inputs.platform }}
          build-mode: ${{ inputs.build-mode }}
          upload-enabled: ${{ inputs.upload-enabled }}
          python-version: ${{ inputs.python-version }}

      - name: Call test action
        uses: ./.github/actions/test
        with:
          test-options: ${{ inputs.test-options }}
          has-gpu: ${{ inputs.has-gpu }}
