name: Test

on:
  workflow_call:
    inputs:
      client-repo:
        required: true
        type: string
      target-device:
        required: true
        type: string
      test-options:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      build-type:
        required: true
        type: string
        description: One of ci / release
      host-platform:
        required: true
        type: string
      dependencies-file:
        required: true
        type: string
        description: path to versions.json relative to the target repo dir
      build-mode:
        required: true
        type: string
      upload-enabled:
        required: true
        type: boolean
      python-version:
        required: false
        type: string
      has-built:
        required: false
        type: string
        description: whether the built stage was launched (and passed)

jobs:
  build:
    name: Test (${{ inputs.host-platform }}, Python "${{ inputs.python-version }}", Use container=${{ inputs.use-container }} )

    permissions:
      id-token: write # This is required for configure-aws-credentials
      contents: read  # This is required for actions/checkout

    runs-on: ${{ inputs.runs-on }}

    container:
      options: -u root --security-opt seccomp=unconfined --privileged --shm-size 16g
      image: condaforge/miniforge3:latest
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    steps:
      - name: Checkout ${{ inputs.client-repo }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        if: ${{ inputs.has-built != 'true' }}
        uses: ./.github/actions/setup
        with:
          client-repo: ${{ inputs.client-repo }}
          build-type: ${{ inputs.build-type }}
          target-device: "${{ inputs.target-device }}"
          host-platform: ${{ inputs.host-platform }}
          build-mode: ${{ inputs.build-mode }}
          upload-enabled: ${{ inputs.upload-enabled }}
          python-version: ${{ inputs.python-version }}

      - name: Call test action
        uses: ./.github/actions/test
        with:
          test-options: ${{ inputs.test-options }}
